package modelo;
// Generated 15/07/2013 11:58:05 by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * Clinica generated by hbm2java
 */
public class Clinica  implements java.io.Serializable {


     private int clinicaId;
     private String clinicaNome;
     private String clinicaEndereco;
     private String clinicaTelefone;
     private String clinicaCidade;
     private String clinicaEstado;
     private String clinicaEmail;
     private String clinicaLogin;
     private String clinicaSenha;
     private Set planos = new HashSet(0);
     private Set medicos = new HashSet(0);

    public Clinica() {
    }

	
    public Clinica(int clinicaId, String clinicaNome) {
        this.clinicaId = clinicaId;
        this.clinicaNome = clinicaNome;
    }
    public Clinica(int clinicaId, String clinicaNome, String clinicaEndereco, String clinicaTelefone, String clinicaCidade, String clinicaEstado, String clinicaEmail, String clinicaLogin, String clinicaSenha, Set planos, Set medicos) {
       this.clinicaId = clinicaId;
       this.clinicaNome = clinicaNome;
       this.clinicaEndereco = clinicaEndereco;
       this.clinicaTelefone = clinicaTelefone;
       this.clinicaCidade = clinicaCidade;
       this.clinicaEstado = clinicaEstado;
       this.clinicaEmail = clinicaEmail;
       this.clinicaLogin = clinicaLogin;
       this.clinicaSenha = clinicaSenha;
       this.planos = planos;
       this.medicos = medicos;
    }
   
    public int getClinicaId() {
        return this.clinicaId;
    }
    
    public void setClinicaId(int clinicaId) {
        this.clinicaId = clinicaId;
    }
    public String getClinicaNome() {
        return this.clinicaNome;
    }
    
    public void setClinicaNome(String clinicaNome) {
        this.clinicaNome = clinicaNome;
    }
    public String getClinicaEndereco() {
        return this.clinicaEndereco;
    }
    
    public void setClinicaEndereco(String clinicaEndereco) {
        this.clinicaEndereco = clinicaEndereco;
    }
    public String getClinicaTelefone() {
        return this.clinicaTelefone;
    }
    
    public void setClinicaTelefone(String clinicaTelefone) {
        this.clinicaTelefone = clinicaTelefone;
    }
    public String getClinicaCidade() {
        return this.clinicaCidade;
    }
    
    public void setClinicaCidade(String clinicaCidade) {
        this.clinicaCidade = clinicaCidade;
    }
    public String getClinicaEstado() {
        return this.clinicaEstado;
    }
    
    public void setClinicaEstado(String clinicaEstado) {
        this.clinicaEstado = clinicaEstado;
    }
    public String getClinicaEmail() {
        return this.clinicaEmail;
    }
    
    public void setClinicaEmail(String clinicaEmail) {
        this.clinicaEmail = clinicaEmail;
    }
    public String getClinicaLogin() {
        return this.clinicaLogin;
    }
    
    public void setClinicaLogin(String clinicaLogin) {
        this.clinicaLogin = clinicaLogin;
    }
    public String getClinicaSenha() {
        return this.clinicaSenha;
    }
    
    public void setClinicaSenha(String clinicaSenha) {
        this.clinicaSenha = clinicaSenha;
    }
    public Set getPlanos() {
        return this.planos;
    }
    
    public void setPlanos(Set planos) {
        this.planos = planos;
    }
    public Set getMedicos() {
        return this.medicos;
    }
    
    public void setMedicos(Set medicos) {
        this.medicos = medicos;
    }




}


