package modelo;
// Generated 15/07/2013 11:58:05 by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * Plano generated by hbm2java
 */
public class Plano  implements java.io.Serializable {


     private int planoId;
     private String planoNome;
     private String planoLogin;
     private String planoEmail;
     private String planoSenha;
     private Set medicos = new HashSet(0);
     private Set pacientes = new HashSet(0);
     private Set clinicas = new HashSet(0);

    public Plano() {
    }

	
    public Plano(int planoId, String planoNome) {
        this.planoId = planoId;
        this.planoNome = planoNome;
    }
    public Plano(int planoId, String planoNome, String planoLogin, String planoEmail, String planoSenha, Set medicos, Set pacientes, Set clinicas) {
       this.planoId = planoId;
       this.planoNome = planoNome;
       this.planoLogin = planoLogin;
       this.planoEmail = planoEmail;
       this.planoSenha = planoSenha;
       this.medicos = medicos;
       this.pacientes = pacientes;
       this.clinicas = clinicas;
    }
   
    public int getPlanoId() {
        return this.planoId;
    }
    
    public void setPlanoId(int planoId) {
        this.planoId = planoId;
    }
    public String getPlanoNome() {
        return this.planoNome;
    }
    
    public void setPlanoNome(String planoNome) {
        this.planoNome = planoNome;
    }
    public String getPlanoLogin() {
        return this.planoLogin;
    }
    
    public void setPlanoLogin(String planoLogin) {
        this.planoLogin = planoLogin;
    }
    public String getPlanoEmail() {
        return this.planoEmail;
    }
    
    public void setPlanoEmail(String planoEmail) {
        this.planoEmail = planoEmail;
    }
    public String getPlanoSenha() {
        return this.planoSenha;
    }
    
    public void setPlanoSenha(String planoSenha) {
        this.planoSenha = planoSenha;
    }
    public Set getMedicos() {
        return this.medicos;
    }
    
    public void setMedicos(Set medicos) {
        this.medicos = medicos;
    }
    public Set getPacientes() {
        return this.pacientes;
    }
    
    public void setPacientes(Set pacientes) {
        this.pacientes = pacientes;
    }
    public Set getClinicas() {
        return this.clinicas;
    }
    
    public void setClinicas(Set clinicas) {
        this.clinicas = clinicas;
    }




}


